var androids =
[
    {
      "id": 1,
      "name": "Dimas Vedre",
      "email": "Sincere@april.biz",
      "street": "Kulas Light",
      "suite": "Apt. 556",
      "city": "Gwenborough",
      "phone": "1-770-736-8031 x56442",
      "img":"https://dl.dropboxusercontent.com./s/0gdx4u1xit5rvh7/images%20%283%29.jpg?dl=0",
      "sallery": 1280,
    },
    {
      "id": 2,
      "name": "Ervin Howell",
      "username": "Antonette",
      "email": "Shanna@melissa.tv",
      "img":"https://dl.dropboxusercontent.com./s/gy50gdtd4ipd1rv/01kishor10.jpg?dl=0",
      "street": "Victor Plains",
      "suite": "Suite 879",
      "city": "Wisokyburgh",
      "phone": "010-692-6593 x09125",
      "sallery": 480,
    },
    {
      "id": 3,
      "name": "Clementine Bauch",
      "username": "Samantha",
      "email": "Nathan@yesenia.net",
      "img":"https://dl.dropboxusercontent.com./s/u0d82h4f5g72ykz/70_Mo-Vlogs.jpg?dl=0",
      "street": "Douglas Extension",
      "suite": "Suite 847",
      "city": "McKenziehaven",
      "phone": "1-463-123-4447",
      "sallery": 380,
     },
    {
      "id": 4,
      "name": "Patricia Lebsack",
      "username": "Karianne",
      "email": "Julianne.OConner@kory.org",
      "img":"https://dl.dropboxusercontent.com./s/694fyld54lzy3lu/25946-12qjhs3.jpg?dl=0",
      "sallery": 560,
      "street": "Hoeger Mall",
      "suite": "Apt. 692",
      "city": "South Elvis",
      "phone": "493-170-9623 x156",
    },
    {
      "id": 5,
      "name": "Chelsey Dietrich",
      "username": "Kamren",
      "email": "Lucio_Hettinger@annie.ca",
      "img":"https://dl.dropboxusercontent.com./s/o3kyhyhw4brh55r/download%20%281%29.jpg?dl=0",
      "sallery": 467,
      "street": "Skiles Walks",
      "suite": "Suite 351",
      "city": "Roscoeview",
      "phone": "(254)954-1289",
    },
    {
      "id": 6,
      "name": "Mrs. Dennis Schulist",
      "username": "Leopoldo_Corkery",
      "email": "Karley_Dach@jasper.info",
      "img":"https://dl.dropboxusercontent.com./s/9m63elbiatdpp57/download%20%282%29.jpg?dl=0",
      "sallery": 858,
      "street": "Norberto Crossing",
      "suite": "Apt. 950",
      "city": "South Christy",
      "phone": "1-477-935-8478 x6430",
     },
    {
      "id": 7,
      "name": "Kurtis Weissnat",
      "username": "Elwyn.Skiles",
      "email": "Telly.Hoeger@billy.biz",
      "img":"https://dl.dropboxusercontent.com./s/m6yakdvxrx7a9qc/download.jpg?dl=0",
      "sallery": 786,
      "street": "Rex Trail",
      "suite": "Suite 280",
      "city": "Howemouth",
      "phone": "210.067.6132",
     },
    {
      "id": 8,
      "name": "Nicholas Runolfsdottir V",
      "username": "Maxime_Nienow",
      "email": "Sherwood@rosamond.me",
      "img":"https://dl.dropboxusercontent.com./s/ai36yyro6wj2s10/images%20%281%29.jpg?dl=0",
      "sallery": 560,
      "street": "Ellsworth Summit",
      "suite": "Suite 729",
      "city": "Aliyaview",
      "phone": "586.493.6943 x140", 
    },
    {
      "id": 9,
      "name": "Glenna Reichert",
      "username": "Delphine",
      "email": "Chaim_McDermott@dana.io",
      "img":"https://dl.dropboxusercontent.com./s/o3jrjrgdgkze05y/images%20%282%29.jpg?dl=0",
      "sallery": 877,
      "street": "Dayna Park",
      "suite": "Suite 449",
      "city": "Bartholomebury",
      "phone": "(775)976-6794 x41206",
    },
    {
      "id": 10,
      "name": "Clementina DuBuque",
      "username": "Moriah.Stanton",
      "email": "Rey.Padberg@karina.biz",
      "img":"https://dl.dropboxusercontent.com./s/3q4vz7clsgl8e3s/images%20%284%29.jpg?dl=0",
      "sallery": 863,
      "street": "Kattie Turnpike",
      "suite": "Suite 198",
      "city": "Lebsackbury",
      "phone": "024-648-3804",
    },
    {
      "id": 11,
      "name": "Clementina DuBuque",
      "username": "Moriah.Stanton",
      "email": "Rey.Padberg@karina.biz",
      "img":"https://dl.dropboxusercontent.com./s/zc5h3hjm4ucvy0s/images%20%285%29.jpg?dl=0",
      "sallery": 435,
      "street": "Kattie Turnpike",
      "suite": "Suite 198",
      "city": "Lebsackbury",
      "phone": "024-648-3804",
     },
    {
      "id": 12,
      "name": "Clementina DuBuque",
      "username": "Moriah.Stanton",
      "email": "Rey.Padberg@karina.biz",
      "img":"https://dl.dropboxusercontent.com./s/sq2l8xfs06qcxjw/images%20%286%29.jpg?dl=0",
      "sallery": 357,
      "street": "Kattie Turnpike",
      "suite": "Suite 198",
      "city": "Lebsackbury",
      "phone": "024-648-3804",
     },
    {
      "id": 13,
      "name": "Clementina DuBuque",
      "username": "Moriah.Stanton",
      "email": "Rey.Padberg@karina.biz",
      "img":"https://dl.dropboxusercontent.com./s/ks2mfxkqcygisax/images%20%287%29.jpg?dl=0",
      "sallery": 787,
      "street": "Kattie Turnpike",
      "suite": "Suite 198",
      "city": "Lebsackbury",
      "phone": "024-648-3804",
     },
    {
      "id": 14,
      "name": "Clementina DuBuque",
      "username": "Moriah.Stanton",
      "email": "Rey.Padberg@karina.biz",
      "img":"https://dl.dropboxusercontent.com./s/a99mnjgxdzkvfqq/images.jpg?dl=0",
      "sallery": 135,
      "street": "Kattie Turnpike",
      "suite": "Suite 198",
      "city": "Lebsackbury",
      "phone": "024-648-3804",
     },
    {
      "id": 15,
      "name": "Clementina DuBuque",
      "username": "Moriah.Stanton",
      "email": "Rey.Padberg@karina.biz",
      "img":"https://dl.dropboxusercontent.com./s/hr786jm0lpil4l9/Linus%20Torvalds.jpeg?dl=0",
      "sallery": 754,
      "street": "Kattie Turnpike",
      "suite": "Suite 198",
      "city": "Lebsackbury",
      "phone": "024-648-3804",
    },
    {
      "id": 16,
      "name": "Clementina DuBuque",
      "username": "Moriah.Stanton",
      "email": "Rey.Padberg@karina.biz",
      "img":"https://dl.dropboxusercontent.com./s/g9zbdorq69cxh94/rahman.jpg?dl=0",
      "sallery": 546,
      "street": "Kattie Turnpike",
      "suite": "Suite 198",
      "city": "Lebsackbury",
      "phone": "024-648-3804",
      
    }
    
  ]

export default androids;